#!/bin/sh
# Shell functions for common operations using fbwhiptail

# Pause for the configured timeout before booting automatically.  Returns 0 to
# continue with automatic boot, nonzero if user interrupted.
pause_automatic_boot()
{
	if IFS= read -t "$CONFIG_AUTO_BOOT_TIMEOUT" -s -n 1 -p \
		"Automatic boot in $CONFIG_AUTO_BOOT_TIMEOUT seconds unless interrupted by keypress... "; then
		return 1 # Interrupt automatic boot
	fi
	return 0 # Continue with automatic boot
}

mount_usb()
{
  # Unmount any previous USB device
  if grep -q /media /proc/mounts ; then
    umount /media || die "Unable to unmount /media"
  fi
  # Mount the USB boot device
  mount-usb && USB_FAILED=0 || ( [ $? -eq 5 ] && exit 1 || USB_FAILED=1 )
  if [ $USB_FAILED -ne 0 ]; then
    whiptail $BG_COLOR_ERROR --title 'USB Drive Missing' \
      --msgbox "Insert your USB drive and press Enter to continue." 16 60
    mount-usb && USB_FAILED=0 || ( [ $? -eq 5 ] && exit 1 || USB_FAILED=1 )
    if [ $USB_FAILED -ne 0 ]; then
      whiptail $BG_COLOR_ERROR --title 'ERROR: Mounting /media Failed' \
        --msgbox "Unable to mount USB device" 16 60
      exit 1
    fi
  fi
}

file_selector()
{
  FILE=""
  FILE_LIST=$1
  MENU_MSG=${2:-"Choose the file"}
  MENU_TITLE=${3:-"Select your File"}

  # create file menu options
  if [ `cat "$FILE_LIST" | wc -l` -gt 0 ]; then
    option=""
    while [ -z "$option" ]
    do
      MENU_OPTIONS=""
      n=0
      while read option
      do
        n=`expr $n + 1`
        option=$(echo $option | tr " " "_")
        MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
      done < $FILE_LIST

      MENU_OPTIONS="$MENU_OPTIONS a Abort"
      whiptail --title "${MENU_TITLE}" \
        --menu "${MENU_MSG} [1-$n, a to abort]:" 20 120 8 \
        -- $MENU_OPTIONS \
        2>/tmp/whiptail || die "Aborting"

      option_index=$(cat /tmp/whiptail)

      if [ "$option_index" = "a" ]; then
        option="a"
        return
      fi

      option=`head -n $option_index $FILE_LIST | tail -1`
      if [ "$option" == "a" ]; then
        return
      fi
    done
    if [ -n "$option" ]; then
      FILE=$option
    fi
  else
    whiptail $BG_COLOR_ERROR --title 'ERROR: No Files Found' \
      --msgbox "No Files found matching the pattern. Aborting." 16 60
    exit 1
  fi
}

show_system_info()
{
  battery_charge="$(print_battery_charge)"
  battery_health="$(print_battery_health)"
  if [ -n $battery_charge -a -n $battery_health ];then
	  battery_status="\nBattery charge: $battery_charge%\nBattery health: $battery_health%\n"
  fi

  memtotal=$(cat /proc/meminfo | grep 'MemTotal' | tr -s ' ' | cut -f2 -d ' ')
  memtotal=$((${memtotal} / 1024 / 1024 + 1))
  cpustr=$(cat /proc/cpuinfo | grep 'model name' | uniq | sed -r 's/\(R\)//;s/\(TM\)//;s/CPU //;s/model name.*: //')
  kernel=$(uname -s -r)
  
  whiptail $BG_COLOR_MAIN_MENU --title 'System Info' \
    --msgbox "${BOARD_NAME}\n\nFW_VER: ${FW_VER}\nKernel: ${kernel}\n\nCPU: ${cpustr}\nRAM: ${memtotal} GB\n$battery_status\n$(fdisk -l | grep -e '/dev/sd.:' -e '/dev/nvme.*:' | sed 's/B,.*/B/')" 16 60
}

# Load a config value to a variable, defaulting to 'n'
load_config_value()
{
  local config_name="$1"
  if grep -q "$config_name" /tmp/config; then
    grep "$config_name=" /tmp/config | tail -n1 | cut -f2 -d '=' | tr -d '"'
  else
    echo n
  fi
}

# Get "Enable" or "Disable" to display in the configuration menu, based on a
# setting value
get_config_display_action()
{
  [ "$1" = "y" ] && echo "Disable" || echo "Enable"
}

# Invert a config value
invert_config()
{
  [ "$1" = "y" ] && echo "n" || echo "y"
}

# Get "Enable" or "Disable" for a config that internally is inverted (because it
# disables a behavior that is on by default).
get_inverted_config_display_action()
{
  get_config_display_action "$(invert_config "$1")"
}

find_extraneous_fw_files()
{
  find /boot/firmware -type f | while read -r extra_file; do
    extra_file="${extra_file#/boot/firmware/}"
    if [ "$extra_file" = README ] || [ "$extra_file" = hashes ]; then continue; fi
    if ! grep -q -e "^[0-9a-f]*  *$extra_file\$" /tmp/firmware/hashes; then
      echo "$extra_file"
    fi
  done
}

find_missing_fw_files()
{
  while read -r fw_hash fw_file; do
    if ! [ -f "/boot/firmware/$fw_file" ]; then
      echo "$fw_file"
    fi
  done </tmp/firmware/hashes 
}

find_bad_fw_files()
{
  while read -r fw_hash fw_file; do
    if [ -f "/boot/firmware/$fw_file" ]; then
      actual_hash="$(sha256sum "/boot/firmware/$fw_file" | cut -f1 -d ' ')"
      if [ "$fw_hash" != "$actual_hash" ]; then
        echo "$fw_file"
      fi
    fi
  done </tmp/firmware/hashes
}

check_blob_jail()
{
  CURRENT_OPTION="$(load_config_value CONFIG_USE_BLOB_JAIL)"
  BLOB_JAIL_QUIET="$(load_config_value CONFIG_BLOB_JAIL_QUIET)"

  if [ "$CURRENT_OPTION" = "y" ]; then
    # extract blobs to /tmp/firmware
    rm -rf /tmp/firmware/* 2>/dev/null
    mkdir -p /tmp/firmware/intel
    mkdir -p /tmp/firmware/ar3k
    for f in `cbfs -l | grep firmware`; do
      cbfs -r "$f" > "/tmp/$f"
      if [[ "$f" == *.lzma ]]; then
        lzma -d "/tmp/$f"
      fi
    done
    BAD="$(find_bad_fw_files)"
    UNK="$(find_extraneous_fw_files)"
    MIS="$(find_missing_fw_files)"
    
    if [ "$BAD" != "" ] && [ "$BLOB_JAIL_QUIET" = "n" ]; then
      whiptail $BG_COLOR_ERROR --title "ERROR: Invalid file(s) found in /boot/firmware" \
        --msgbox "The following file(s) failed checksum validation\nand will be replaced with known good copies:\n\n$BAD\n\n" 30 90
    fi
    if [ "$UNK" != "" ] && [ "$BLOB_JAIL_QUIET" = "n" ]; then
      whiptail $BG_COLOR_ERROR --title "ERROR: Unknown file(s) found in /boot/firmware" \
        --msgbox "The following file(s) are not known good WiFi firmware\nfiles and will be removed:\n\n$UNK\n\n" 30 90
    fi
    if [ "$MIS" != "" ] && [ "$BLOB_JAIL_QUIET" = "n" ]; then
      whiptail $BG_COLOR_ERROR --title "ERROR: Missing file(s) found in /boot/firmware" \
        --msgbox "The following file(s) are missing from /boot/firmware\nand will be copied from flash:\n\n$MIS\n\n" 30 90
    fi
    if [[ "$MIS" != "" || "$BAD" != "" || "$UNK" != "" ]]; then
      echo -e "Synchronizing firmware files in /boot/firmware/"
      # remount boot RW
      mount -o rw,remount /boot
      # create and clear dir
      mkdir -p /boot/firmware/ && rm -rf /boot/firmware/* 2>/dev/null
      # copy files /boot/firmware
      cp -r /tmp/firmware/* /boot/firmware/
      # remount /boot RO
      mount -o ro,remount /boot
    fi
    # ensure kernel param added
    PARAMS="$CONFIG_BOOT_KERNEL_ADD"
    if ! echo "$PARAMS" | grep -q "firmware_class"; then
      CONFIG_BOOT_KERNEL_ADD="${CONFIG_BOOT_KERNEL_ADD} firmware_class.path=/boot/firmware/"
    fi
  else
    # remove files from /boot/firmware
    if ls /boot/firmware/ >/dev/null 2>&1; then
      echo -e "Clearing firmware files from /boot/firmware"
      # remount boot RW
      mount -o rw,remount /boot
      # clear files
      rm -rf /boot/firmware/
      # remount boot RO
      mount -o ro,remount /boot
    fi
    # remove kernel param
    CONFIG_BOOT_KERNEL_ADD="${CONFIG_BOOT_KERNEL_ADD//firmware_class.path=\/boot\/firmware\//}"
  fi
  # ensure BOOT_KERNEL_ADD persisted
  replace_config /etc/config.user "CONFIG_BOOT_KERNEL_ADD" "$CONFIG_BOOT_KERNEL_ADD"
  combine_configs
}
